version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  bot:
    build: .
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:

